### ISSUE TITLE
PDF url not accessible

### ISSUE THREAD

**Issue by uri200** [Emano-Waldeck/pdf-reader#16]
Since few days ago we were able to get the URL of the file from the top right corner menu. But that option has disappeared now with v0.3.1

Note that since this is an extension, the address bar shows the url of the extension. Not the URL of the file.

![image](https://user-images.githubusercontent.com/16157139/181806419-a65d95f3-c0ff-4502-985c-914060948989.png)

**Comment by Emano-Waldeck** [comment]
The bookmark icon now copies the current page to the clipboard, which is essentially the same thing.

**Comment by uri200** [comment]
Awesome. I may have missed that!! It works. Thanks for quick answer

As a suggestion, (just my opinion), maybe a different icon may help people like me :D
