### ISSUE TITLE
Let user enter zoom level manually

### ISSUE THREAD

**Issue by jdanbrown** [Emano-Waldeck/pdf-reader#21]
Sometimes I'd like to zoom to 115% or 125% or 140%, but the `zoomIn()`/`zoomOut()` levels only allow a fixed set of zoom values. It'd be useful to add a "Custom Zoom..." option to allow the user to manually type in a zoom level.

As a power-user workaround, here's how to do it in the dev console:

```js
PDFViewerApplication.pdfViewer.currentScaleValue = 1.15
```

**Comment by jdanbrown** [comment]
Awesome, thank you!

**Comment by Emano-Waldeck** [comment]
Cheers
