### ISSUE TITLE
how do I set these pdf settings?

### ISSUE THREAD

**Issue by 123SONIC321** [Emano-Waldeck/pdf-reader#25]
I used to use another extension that used HTML5 to read PDFs. In its options page, it had options such as: "enableHandToolOnLoad", "cursorToolOnLoad", "showPreviousViewOnLoad". How can I add these settings to this extension?

**Comment by Emano-Waldeck** [comment]
There are two new options on the right-click context menu (as of the next release)

1. "Default Tool" to set hand or select tool initially.
2. "Disable Previous View History" to disable PDF opening history.

**Comment by 123SONIC321** [comment]
Thank you; your extension is amazing (flawless dark mode)
it would be so cool if you could also add some of these settings for the next release
![image](https://github.com/Emano-Waldeck/pdf-reader/assets/99527351/1d598cc5-6722-494e-adac-b6c239558b68)
thanks again for the amazing extension ♥
