### ISSUE TITLE
Set default zoom level?

### ISSUE THREAD

**Issue by Timoyoungster** [Emano-Waldeck/pdf-reader#26]
Hello,

is there a way to specify a default zoom level for the pdf reader to use?
I'd like to have all pdfs open in 'Page Width' zoom mode.

PS: Is there something like an official documentation or sth. for this? Because I couldn't find anything, which is why I am creating this issue post now.

**Comment by Emano-Waldeck** [comment]
As of the next release, there is a new option in the right-click context menu to change the default zoom.

**Comment by Timoyoungster** [comment]
Thank you!
